<?php

namespace FormationBundle\Repository;

/**
 * CertificatePaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificatePaymentRepository extends \Doctrine\ORM\EntityRepository
{
}
