<?php

namespace FormationBundle\Repository;

/**
 * FormationPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationPaymentRepository extends \Doctrine\ORM\EntityRepository
{
}
