<?php

namespace FormationBundle\Repository;

/**
 * InstructorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstructorRepository extends \Doctrine\ORM\EntityRepository
{
}
