instructor_index:
    path:     /
    defaults: { _controller: "FormationBundle:Instructor:index" }
    methods:  GET

instructor_show:
    path:     /{id}/show
    defaults: { _controller: "FormationBundle:Instructor:show" }
    methods:  GET

instructor_new:
    path:     /new
    defaults: { _controller: "FormationBundle:Instructor:new" }
    methods:  [GET, POST]

instructor_edit:
    path:     /{id}/edit
    defaults: { _controller: "FormationBundle:Instructor:edit" }
    methods:  [GET, POST]

instructor_delete:
    path:     /{id}/delete
    defaults: { _controller: "FormationBundle:Instructor:delete" }
    methods:  DELETE
